variable_attrs = {
    "u10": {"long_name": "u component of 10-meter wind", "standard_name": "u10_wind_velocity", "units": "m s-1", "positive": "east",},
    "v10": {"long_name": "v component of 10-meter wind", "standard_name": "v10_wind_velocity", "units": "m s-1", "positive": "north",},
    "uzonal_surface": {"long_name": "u component of wind at midpoint of lowest model layer", "standard_name": "u_surface_component", "units": "m s-1", "positive": "east",},
    "umeridional_surface": {"long_name": "v component of wind at midpoint of lowest model layer", "standard_name": "v_surface_component", "units": "m s-1", "positive": "north",},
    "uzonal_1km": {"long_name": "u component of wind at 1 km AGL", "standard_name": "u_1km_component", "units": "m s-1", "positive": "east",},
    "umeridional_1km": {"long_name": "v component of wind at 1 km AGL", "standard_name": "v_1km_component", "units": "m s-1", "positive": "north",},
    "uzonal_6km": {"long_name": "u component of wind at 6 km AGL", "standard_name": "u_6km_component", "units": "m s-1", "positive": "east",},
    "umeridional_6km": {"long_name": "v component of wind at 6 km AGL", "standard_name": "v_6km_component", "units": "m s-1", "positive": "north",},
    'uzonal_50hPa': {"long_name": "u component of wind at 50 hPa", "standard_name": "u_6km_component", "units": "m s-1", "positive": "east",},
    'uzonal_100hPa': {"long_name": "u component of wind at 100 hPa", "standard_name": "u_6km_component", "units": "m s-1", "positive": "east",},
    'uzonal_200hPa': {"long_name": "u component of wind at 200 hPa", "standard_name": "u_6km_component", "units": "m s-1", "positive": "east",},
    'uzonal_250hPa': {"long_name": "u component of wind at 250 hPa", "standard_name": "u_6km_component", "units": "m s-1", "positive": "east",},
    'uzonal_500hPa': {"long_name": "u component of wind at 500 hPa", "standard_name": "u_6km_component", "units": "m s-1", "positive": "east",},
    'uzonal_700hPa': {"long_name": "u component of wind at 700 hPa", "standard_name": "u_6km_component", "units": "m s-1", "positive": "east",},
    'uzonal_850hPa': {"long_name": "u component of wind at 850 hPa", "standard_name": "u_6km_component", "units": "m s-1", "positive": "east",},
    'uzonal_925hPa': {"long_name": "u component of wind at 925 hPa", "standard_name": "u_6km_component", "units": "m s-1", "positive": "east",},
    'umeridional_50hPa': {"long_name": "v component of wind at 50 hPa", "standard_name": "v_6km_component", "units": "m s-1", "positive": "north",},
    'umeridional_100hPa': {"long_name": "v component of wind at 100 hPa", "standard_name": "v_6km_component", "units": "m s-1", "positive": "north",},
    'umeridional_200hPa': {"long_name": "v component of wind at 200 hPa", "standard_name": "v_6km_component", "units": "m s-1", "positive": "north",},
    'umeridional_250hPa': {"long_name": "v component of wind at 250 hPa", "standard_name": "v_6km_component", "units": "m s-1", "positive": "north",},
    'umeridional_500hPa': {"long_name": "v component of wind at 500 hPa", "standard_name": "v_6km_component", "units": "m s-1", "positive": "north",},
    'umeridional_700hPa': {"long_name": "v component of wind at 700 hPa", "standard_name": "v_6km_component", "units": "m s-1", "positive": "north",},
    'umeridional_850hPa': {"long_name": "v component of wind at 850 hPa", "standard_name": "v_6km_component", "units": "m s-1", "positive": "north",},
    'umeridional_925hPa': {"long_name": "v component of wind at 925 hPa", "standard_name": "v_6km_component", "units": "m s-1", "positive": "north",},    
}